--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_app_task; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.main_app_task (
    id bigint NOT NULL,
    description text NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.main_app_task OWNER TO jialingye;

--
-- Name: main_app_task_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.main_app_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_app_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_app_task; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO main_app_task VALUES (7, 'apple', 47);
INSERT INTO main_app_task VALUES (8, 'orange', 47);
INSERT INTO main_app_task VALUES (9, 'banana', 47);
INSERT INTO main_app_task VALUES (10, 'syntax', 65);
INSERT INTO main_app_task VALUES (11, 'data types', 65);
INSERT INTO main_app_task VALUES (12, 'functions', 65);
INSERT INTO main_app_task VALUES (13, 'control structures', 65);
INSERT INTO main_app_task VALUES (14, 'models', 66);
INSERT INTO main_app_task VALUES (15, 'views', 66);
INSERT INTO main_app_task VALUES (16, 'templates', 66);
INSERT INTO main_app_task VALUES (17, 'URL ', 66);
INSERT INTO main_app_task VALUES (18, 'chicken wing', 76);
INSERT INTO main_app_task VALUES (19, 'egg tarts', 76);
INSERT INTO main_app_task VALUES (20, 'ice cream', 76);


--
-- Name: main_app_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.main_app_task_id_seq', 20, true);


--
-- Name: main_app_task main_app_task_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_task
    ADD CONSTRAINT main_app_task_pkey PRIMARY KEY (id);


--
-- Name: main_app_task_project_id_f6756392; Type: INDEX; Schema: public; Owner: jialingye
--

CREATE INDEX main_app_task_project_id_f6756392 ON public.main_app_task USING btree (project_id);


--
-- Name: main_app_task main_app_task_project_id_f6756392_fk_main_app_miniproject_id; Type: FK CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_task
    ADD CONSTRAINT main_app_task_project_id_f6756392_fk_main_app_miniproject_id FOREIGN KEY (project_id) REFERENCES public.main_app_miniproject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

