--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_app_group; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.main_app_group (
    id bigint NOT NULL,
    title character varying(150) NOT NULL
);


ALTER TABLE public.main_app_group OWNER TO jialingye;

--
-- Name: main_app_group_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.main_app_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_app_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_app_group; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO public.main_app_group VALUES (1, 'Python Basics');
INSERT INTO public.main_app_group VALUES (2, 'To-do');
INSERT INTO public.main_app_group VALUES (3, 'Important');


--
-- Name: main_app_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.main_app_group_id_seq', 3, true);


--
-- Name: main_app_group main_app_group_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_group
    ADD CONSTRAINT main_app_group_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

