--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_app_miniproject; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.main_app_miniproject (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    complete boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    mapproject_id bigint NOT NULL,
    parent_id bigint
);


ALTER TABLE public.main_app_miniproject OWNER TO jialingye;

--
-- Name: main_app_miniproject_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.main_app_miniproject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_app_miniproject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_app_miniproject; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO main_app_miniproject VALUES (61, 'Python Basic 2', 'Basic ', false, '2023-07-06 14:56:32.3445-05', 2, 5);
INSERT INTO main_app_miniproject VALUES (5, 'Python Basic', '1', false, '2023-07-05 12:52:36.390403-05', 2, NULL);
INSERT INTO main_app_miniproject VALUES (65, 'Basic Python', 'Understand the Basics of Python: Django is a web framework written in Python, so it''s essential to have a good understanding of Python programming. If you''re new to Python, start by learning the fundamentals of the language, such as syntax, data types, functions, and control structures.', false, '2023-07-06 15:10:26.923205-05', 3, NULL);
INSERT INTO main_app_miniproject VALUES (66, 'Django Fundamentals', 'Learn the Django Fundamentals: Familiarize yourself with the core concepts and components of Django. Start with the official Django documentation, which provides an excellent overview of Django''s features, including models, views, templates, and URL routing. Work through tutorials and examples to gain hands-on experience with Django''s basic functionality.', false, '2023-07-06 15:11:05.688573-05', 3, 65);
INSERT INTO main_app_miniproject VALUES (67, 'Build Real-World Projects', 'Practice is key to mastering Django. Start building small, self-contained projects to reinforce your understanding of Django''s concepts and best practices. As you progress, take on more complex projects that involve database interactions, user authentication, and third-party integrations. This practical experience will deepen your understanding and prepare you for real-world Django development.', false, '2023-07-06 15:11:40.225328-05', 3, 66);
INSERT INTO main_app_miniproject VALUES (69, 'Define the Project Scope', 'Clearly define the purpose and goals of your project. Determine the key features, functionality, and requirements. Break down the project into smaller tasks and prioritize them.', false, '2023-07-06 15:13:51.294239-05', 3, 67);
INSERT INTO main_app_miniproject VALUES (70, 'Design the Database Schema:', 'Identify the data entities and relationships required for your project. Design the database schema using Django''s Object-Relational Mapping (ORM) features. Create Django models to represent the database tables and define the fields, relationships, and constraints.', false, '2023-07-06 15:14:11.377033-05', 3, 67);
INSERT INTO main_app_miniproject VALUES (74, 'Views/URL', 'Define the views that handle the business logic of your application. Write functions or classes that process user requests, fetch data from the database, and render templates. Map these views to URLs using Django''s URL routing system.', false, '2023-07-06 15:19:35.828215-05', 3, 67);
INSERT INTO main_app_miniproject VALUES (75, 'Develop Templates', ' Design and implement the user interface using HTML, CSS, and JavaScript. Create templates that present the data from your views and models to the users. Utilize Django''s template language to dynamically render data and handle control flow logic.', false, '2023-07-06 15:20:33.833057-05', 3, 67);
INSERT INTO main_app_miniproject VALUES (76, 'Party Food', '10 dishes', false, '2023-07-06 18:03:38.02611-05', 5, NULL);
INSERT INTO main_app_miniproject VALUES (77, 'Decoration', 'colorful theme', false, '2023-07-06 18:04:28.579356-05', 5, NULL);
INSERT INTO main_app_miniproject VALUES (78, 'Costco ', 'buy 5 ', false, '2023-07-06 18:04:50.688055-05', 5, 76);
INSERT INTO main_app_miniproject VALUES (79, 'take out', 'sandwiches', false, '2023-07-06 18:05:19.154252-05', 5, 78);
INSERT INTO main_app_miniproject VALUES (80, 'utensil', 'fork and spoon', false, '2023-07-06 18:06:06.888147-05', 5, 78);
INSERT INTO main_app_miniproject VALUES (81, 'balloon', 'white', false, '2023-07-06 18:06:20.7933-05', 5, 77);
INSERT INTO main_app_miniproject VALUES (47, 'Python Basic 2.5', 'Learn Expert', false, '2023-07-06 11:13:08.143249-05', 2, 5);


--
-- Name: main_app_miniproject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.main_app_miniproject_id_seq', 82, true);


--
-- Name: main_app_miniproject main_app_miniproject_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_miniproject
    ADD CONSTRAINT main_app_miniproject_pkey PRIMARY KEY (id);


--
-- Name: main_app_miniproject_mapproject_id_9b6fb4e7; Type: INDEX; Schema: public; Owner: jialingye
--

CREATE INDEX main_app_miniproject_mapproject_id_9b6fb4e7 ON public.main_app_miniproject USING btree (mapproject_id);


--
-- Name: main_app_miniproject_parent_id_4e492bc1; Type: INDEX; Schema: public; Owner: jialingye
--

CREATE INDEX main_app_miniproject_parent_id_4e492bc1 ON public.main_app_miniproject USING btree (parent_id);


--
-- Name: main_app_miniproject main_app_miniproject_mapproject_id_9b6fb4e7_fk_main_app_; Type: FK CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_miniproject
    ADD CONSTRAINT main_app_miniproject_mapproject_id_9b6fb4e7_fk_main_app_ FOREIGN KEY (mapproject_id) REFERENCES public.main_app_mapproject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_app_miniproject main_app_miniproject_parent_id_4e492bc1_fk_main_app_; Type: FK CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_miniproject
    ADD CONSTRAINT main_app_miniproject_parent_id_4e492bc1_fk_main_app_ FOREIGN KEY (parent_id) REFERENCES public.main_app_miniproject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

