# Generated by Django 4.2.2 on 2023-07-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapproject',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
