# Generated by Django 4.2.2 on 2023-07-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_mapproject_options_remove_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('projects', models.ManyToManyField(to='main_app.mapproject')),
            ],
        ),
    ]
